### PR TITLE
Added several icons

### PR DESCRIPTION
**Pull request by pie75**
These are most of the icons for the apps that i have installed on my own phone, (and the variants of those apps, where i knew to look for them.)

i've also added Google Voice Search to the list of icons which use the default Google App icon, since it wasn't there when I checked.

i took great liberty with the Karma FW icon because it was both too simple, and noisy, at the same time. One that matches the original more closely can be made if desired.

i fully intend to finish the rest of the icons for the apps on my phone, so that could be added to this PR before merging, if desired.

### CODE REVIEW

**Comment by JapanYoshi** [comment]
These are great! Just a few things I would change:

* Book Reader should use the same book template as the Dictionary icons.
* The arrow in Loop Habits looks a bit too geometric.
* I've rounded out the straight edges in Nihonoari.

I've attached my revisions to this comment: 
[svg.zip](https://github.com/JapanYoshi/dollphone-foss/files/14545717/svg.zip)

**Comment by pie75** [comment]
Thank you !
i hadn't noticed the book template; i'll keep in mind that there are templates, as i keep working.

i have nothing to revise on your revisions, so you can commit them to my branch if you want -- or i can do so, if you prefer.

**Comment by JapanYoshi** [comment]
I'm not a fan of the Google Voice Search icon. I think the original icon is supposed to represent a mic with a long head instead of the round one in the icon right now.

**Comment by pie75** [comment]
i agree that the original icon represents a different type of microphone.

i chose the ball type because it was already in the other voice-related icons, and it seemed cuter, so more consistent.
i also usually find it less intuitive that the top of long mics must tilt away from the speaker, whereas ball mics are pointed at the speaker, as shown in the icon. i think it gives more of a "here, speak into me," vibe.

i'll draft the other microphone for comparison.

**Comment by JapanYoshi** [comment]
google_voice_search
Here's my attempt.

**Comment by pie75** [comment]
i think that's great!

google_voice_search
This is mine.

i guess it's not as soft. still getting the hang of the bubbly thing, i think.

**Comment by pie75** [comment]
i've made some variants of Obsidian. One uses gradients liberally but approximates the original more closely. the other avoids gradients entirely, but i think it has a stranger appearance.
| gradient | solid |
| ----------- | ------ |
 obsidian_1 | obsidian

**Comment by JapanYoshi** [comment]
I've noticed that we've both made a Suntimes icon. Which one should we keep?
https://github.com/JapanYoshi/dollphone-foss/blob/main/app/src/main/res/drawable-nodpi/suntimes.png

Also, I'd like to include your contributions in the next version, since Obsidian (10x, \#1 most requested), Syncthing (7x), and Puzzles (5x) are all often requested. Can you tell me if you're ready?

**Pull request merged**
