### PR TITLE
Create email_parser.py

### PR DESCRIPTION
**Pull request by Donnnno**
This is the Arcticons email parser script, it should work for your project too.

Here's how I use it:
1. I download all request mails to a folder called `/mail`, using thunderbird.
2. Then I open the terminal (make sure to have Python 3 installed for this)
3. CD to the directory something like `cd GitHub/dollphone-foss/scripts`
4. then run it by typing `python3 email_parser.py mail_folder_path appfilter_path 
5. That should return a requetst.txt and an updatable.txt file

`email_parser.py [-h] folder_path appfilter_path [requests_path]`

You might wanna tweak the config too:

```
config = {
    "request_limit": 50,
    "months_limit": 6,
    "min_requests": 5,
    "date_format": "X%d %B %Y",
}
```

### CODE REVIEW

**Comment by JapanYoshi** [comment]
I've never used Thunderbird so I don't know what you're talking about, unfortunately

**Comment by Donnnno** [comment]
Thunderbird is a pretty convenient mail client, check it out: https://www.thunderbird.net/
But it isn't necessary when your mail provider allows downloading mails. 

icons aren't extracted. Instead you get links to multiple appstores that will preview the icon on their page, like this:


```
-------------------------------------------------------
11821 Requested Apps Pending (Updated 5 March 2024)
-------------------------------------------------------

<!-- Widgetable -->
<item component="ComponentInfo{com.widgetable.theme.android/com.widgetable.theme.android.ui.MainActivity}" drawable="widgetable"/>
https://play.google.com/store/apps/details?id=com.widgetable.theme.android
https://f-droid.org/en/packages/com.widgetable.theme.android/
https://apt.izzysoft.de/fdroid/index/apk/com.widgetable.theme.android
https://galaxystore.samsung.com/detail/com.widgetable.theme.android
https://www.ecosia.org/search?q=com.widgetable.theme.android
Requested 17 times
Last requested 1709418957.0
    
<!-- Shadow Fight 4 -->
<item component="ComponentInfo{com.nekki.shadowfightarena/com.nekki.unityplugins.NekkiNativeActivity}" drawable="shadow_fight_4"/>
https://play.google.com/store/apps/details?id=com.nekki.shadowfightarena
https://f-droid.org/en/packages/com.nekki.shadowfightarena/
https://apt.izzysoft.de/fdroid/index/apk/com.nekki.shadowfightarena
https://galaxystore.samsung.com/detail/com.nekki.shadowfightarena
https://www.ecosia.org/search?q=com.nekki.shadowfightarena
Requested 16 times
Last requested 1709520335.0
    
<!-- Audire -->
<item component="ComponentInfo{com.alexmercerind.audire/com.alexmercerind.audire.ui.MainActivity}" drawable="audire"/>
https://play.google.com/store/apps/details?id=com.alexmercerind.audire
https://f-droid.org/en/packages/com.alexmercerind.audire/
https://apt.izzysoft.de/fdroid/index/apk/com.alexmercerind.audire
https://galaxystore.samsung.com/detail/com.alexmercerind.audire
https://www.ecosia.org/search?q=com.alexmercerind.audire
Requested 15 times
Last requested 1709554377.0
```

**Comment by JapanYoshi** [comment]
> icons aren't extracted. Instead you get links to multiple appstores that will preview the icon on their page, like this:
> 
> ```
> -------------------------------------------------------
> 11821 Requested Apps Pending (Updated 5 March 2024)
> -------------------------------------------------------
> 
> 
> <item component="ComponentInfo{com.widgetable.theme.android/com.widgetable.theme.android.ui.MainActivity}" drawable="widgetable"/>
> https://play.google.com/store/apps/details?id=com.widgetable.theme.android
> https://f-droid.org/en/packages/com.widgetable.theme.android/
> https://apt.izzysoft.de/fdroid/index/apk/com.widgetable.theme.android
> https://galaxystore.samsung.com/detail/com.widgetable.theme.android
> https://www.ecosia.org/search?q=com.widgetable.theme.android
> Requested 17 times
> Last requested 1709418957.0

That's a lot of lost data! A lot of my time contributing to Arcticons has been wasted on checking Play Store, then F-Droid, then IzzyOnDroid, to see which store has that app. In cases like Sonolus where it's not on any storefront, that's a lot of wasted time, just to see how the icon originally looks. The app zips up the source icons, so without that archive, my workflow would be way slower.

Are you sure there's no Python library capable of extracting the PNG files from the ZIP, detecting duplicates, and auto-renaming the images when saving them for later?

**Comment by Donnnno** [comment]
I admit, it isn't ideal, but manually uploading icon requests to GitHub is also a struggle. ([we've been there too](https://github.com/Arcticons-Team/Arcticons/issues?page=28&q=is%3Aissue+is%3Aclosed))


> Are you sure there's no Python library capable of extracting the PNG files from the ZIP, detecting duplicates, and auto-renaming the images when saving them for later?

I'm not a Python expert, but it's probably possible. (have to check that with someone who knows it better)


> Also, I'm using Gmail right now. Can it download emails or should I set up another email provider for Dollphone?

Should be possible with thunderbird: https://support.mozilla.org/en-US/kb/thunderbird-and-gmail

**Comment by Donnnno** [comment]
> Are you sure there's no Python library capable of extracting the PNG files from the ZIP, detecting duplicates, and auto-renaming the images when saving them for later?

Maybe @Kaiserdragon2 knows, the script scans the zip content already, right?

**Comment by Kaiserdragon2** [comment]
Yes the script scans the zips already it would be possible to also save the png but sometimes the needed to be renamed for later use because some apps are named the same then the drawable entry would need a rewrite also. But it is possible.

**Comment by Kaiserdragon2** [comment]
> Yes the script scans the zips already it would be possible to also save the png but sometimes the needed to be renamed for later use because some apps are named the same then the drawable entry would need a rewrite also. But it is possible. Then it would also be possible to show them on the request site.

I might be able to create something like this but it will take a bit of time.

**Comment by Donnnno** [comment]
Only if you wanna, don't feel any pressure to create anything ;)

**Comment by Kaiserdragon2** [comment]
I think it would be a nice thing to have maybe if its works good we could than backport it to arcticons

**Pull request closed without merging**
