### PR TITLE
Requests dashboard

### PR DESCRIPTION
**Pull request by Donnnno**
Need to add these for dollphone-foss too
Scherm­afbeelding 2024-03-06 om 09 43 54

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
This looks good.
Now the mail parser script is needed to generate the request.txt

**Comment by Donnnno** [comment]
Thanks for the check, good to know that it's easy to share!

**Comment by Kaiserdragon2** [comment]
A little Preview
https://github.com/JapanYoshi/dollphone-foss/assets/8929967/58bd081c-620f-4b48-9dc1-4b0abeeb0978

**Comment by Donnnno** [comment]
Wow, that's sick!

**Pull request closed without merging**
