### PR TITLE
added some icons

### PR DESCRIPTION
**Pull request by quantenzitrone**
I plan to do a few icons, but before I continue, I wanted to ask for some feedback.

### CODE REVIEW

**Comment by JapanYoshi** [comment]
You've forgotten to add a drop shadow. The triangle doesn't look centered either.

[I've committed my revision to your branch](https://github.com/quantenzitrone/dollphone-foss/commit/2ce710b9415b163887a67751d4899d136270e827).

**Comment by quantenzitrone** [comment]
Feedback on obtainium and organic maps would be appreciated :)

**Comment by JapanYoshi** [comment]
Obtainium: Looks nice, but I've made the arrow in the negative space more obvious by pushing the lines outward from the center. I also layered the outline behind the logo so that the inner corners looked less gross.
obtainium

Organic Maps: Nice! I made the map pin's outline more smooth and rounded, and adjusted the positioning.
organic_maps

**Comment by quantenzitrone** [comment]
For Organic Maps, I intentionally move the shadow ~3.5px down instead of 4px because I thought the small gap between the arm/stalk and its shadow looked weird.

**Comment by quantenzitrone** [comment]
I tried to give the bug a face, but it always looked bad

P.S. I have GPG too now \ö/

**Comment by quantenzitrone** [comment]
You can use https://github.com/Kaiserdragon2/IconRequest to check icon packs for missing icons and duplicate appfilter entries. I went through everything the app could find in v1.1.0

**Pull request merged**
