### PR TITLE
Updated the Github Workflow that it should work correct 

### PR DESCRIPTION
**Pull request by Kaiserdragon2**

### CODE REVIEW

**Comment by JapanYoshi** [comment]
What does this do?

**Comment by Kaiserdragon2** [comment]
This fixes the Github workflow that combines the appfilter files from pull request and puts it in the docs/assets folder.
there the request site can access it and filter the already done request

**Comment by JapanYoshi** [comment]
What does this method have over [email_parser.bat](https://github.com/JapanYoshi/dollphone-foss/blob/main/scripts/email_parser.bat)? I’d still have to manually place the emails in the right folder to update the list; what sense does it make to obfuscate when it gets updated, and make it impossible to update the list fully offline?

**Comment by Kaiserdragon2** [comment]
it doesn't replace the email parser
it is to filter icons that somebody as done and are in a pull request so that there aren't shown on the request site
that should prevent that two people do the same icon from the request site.

**Pull request merged**
